#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service() {
	/usr/sbin/sfp-speed-control apply
}

reload_service() {
	/usr/sbin/sfp-speed-control apply
}

service_triggers() {
	procd_add_reload_trigger "sfp-speed"
}
